return {
    PlayerDamage = 24,
    PlayerAttackInterval = 0.45,
    AttackRange = 6,
    MaxDuration = 120,
    Tiers = {
        Plain = {Count = 2, Health = 24, Damage = 2, Speed = 11, AttackInterval = 1.8},
        Salted = {Count = 2, Health = 32, Damage = 3, Speed = 12, AttackInterval = 1.8},
        Golden = {Count = 3, Health = 40, Damage = 4, Speed = 13, AttackInterval = 1.8},
        Rainbow = {Count = 3, Health = 48, Damage = 4, Speed = 14, AttackInterval = 1.7},
        Cosmic = {Count = 4, Health = 56, Damage = 5, Speed = 15, AttackInterval = 1.6},
    },
}
